spring.application.name=academia-api

# Remove o banner ASCII
spring.main.banner-mode=off

# Mostra logs importantes (INFO)
logging.level.root=INFO

# Reduz barulho do Hibernate
logging.level.org.hibernate=ERROR
logging.level.org.springframework=INFO

# Evita SQL poluindo o terminal
spring.jpa.properties.hibernate.format_sql=false


# Dados do banco
spring.datasource.url=jdbc:mysql://localhost:3306/academia_db
spring.datasource.username=root
spring.datasource.password=

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
